BEGIN TRANSACTION;
DROP TABLE Place_Voyageur;
DROP TABLE Billet_Trajet;
DROP TABLE Billet;
DROP TYPE payem;
DROP TABLE Gare_Intermediaire;
DROP TABLE Trajet;
DROP TABLE Train;
DROP TABLE Type_Train;
DROP TABLE Gare_Interet;
DROP TABLE Point_Interet;
DROP TYPE typei;
DROP TABLE SalarieGare;
DROP TABLE Gare;
DROP TABLE Voyageur;
DROP TABLE Salarie;
DROP TYPE typet;
DROP TYPE typep;
DROP TABLE Personne;
DROP SEQUENCE IdPers;
DROP TYPE typev;
DROP TABLE Ville;
COMMIT;
