BEGIN TRANSACTION;
--DROP TABLE Place_Voyageur cascade;
--DROP TABLE Billet_Trajet cascade;
DROP TABLE Billet cascade;
DROP TYPE payem cascade;
--DROP TABLE Gare_Intermediaire cascade;
DROP TABLE Trajet cascade;
DROP TABLE Train cascade;
DROP TABLE Type_Train cascade;
DROP TABLE Gare_Interet cascade;
DROP TABLE Point_Interet cascade;
DROP TYPE typei cascade;
DROP TABLE Salarie_Gare cascade;
DROP TABLE Gare cascade;
DROP TABLE Voyageur cascade;
DROP TABLE Salarie cascade;
DROP TYPE typet cascade;
DROP TYPE typep cascade;
DROP TABLE Personne cascade;
DROP TABLE Ville cascade;
DROP FUNCTION insert_ville() cascade;
COMMIT;
